version: 2

models:
  - name: dim_listings_cleansed
    decription: Cleansed table which contains Airbnb listings.
    columns:
      - name: listing_id
        description: Primary key for the listing.
        tests: 
          - unique
          - not_null

      - name: host_id
        description: The hosts's id. References the host table.
        tests:
          - not_null
          - relationships:
              to: ref('dim_hosts_cleansed')
              field: host_id

      - name: room_type
        description: Type of the apartment/room
        tests:
          - accepted_values:
              values: ['Entire home/apt',
                     'Private room',
                     'Shared room',
                     'Hotel room']

      - name: minimum_nights
        description: '{{ doc("dim_listings_cleansed_minimum_nights") }}'
        tests:
          - positive_value

  - name: dim_hosts_cleansed
    description: Cleansed raw hosts, handled null host name.
    columns:
      - name: host_id
        description: Primary key of the table.
        tests:
          - not_null
          - unique

      - name: host_name
        description: Name of the host. Anonymous wherever information not available.
        tests:
          - not_null

      - name: is_superhost
        description: Boolean value; tells whether the host is a superhost or not.
        tests:
          - accepted_values:
              values: ['t', 'f']

  - name: fct_review
    columns:
      - name: listing_id
        tests:
          - relationships:
              to: ref('dim_listings_cleansed')
              field: listing_id

      - name: reviewer_name
        tests:
          - not_null

      - name: review_sentiment
        tests:
          - accepted_values:
              values: ['positive', 'neutral', 'negative']